# Set the base image
FROM openjdk:8-jre-slim
EXPOSE 8080
ADD target/service.jar service.jar
COPY autostart-prod.sh /root/autostart-prod.sh
RUN chmod 755 /root/autostart-prod.sh
RUN apt-get update
RUN apt-get -y install curl
RUN apt-get -y install unzip
RUN apt-get -y install wget
RUN wget -O dd-java-agent.jar 'https://dtdg.co/latest-java-tracer'
ENTRYPOINT ["/root/autostart-prod.sh"]
